/**********************************************************************
 * Extern for BalloonEditor
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var BalloonEditor = {
  "build": {
    "config": {
      "image": {
        "toolbar": {}
      },
      "toolbar": {
        "items": {}
      }
    },
    "plugins": {}
  },
  create: function () {
  }
};
/**********************************************************************
 * End Generated Extern for BalloonEditor
 /**********************************************************************/